In [1]:
import numpy as np
A=np.random.binomial(1, 0.3, 20)
A

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [2]:
B=np.random.binomial(1, 0.3, 300000)

D=np.array([])
for i in range(500):
    C=B[i*600:(i+1)*600]
    avg=np.mean(C)
    D=np.append(D,avg)
    


In [3]:
D

array([0.31833333, 0.30666667, 0.33666667, 0.285     , 0.27833333,
       0.31166667, 0.31166667, 0.305     , 0.305     , 0.31833333,
       0.3       , 0.28833333, 0.30833333, 0.31333333, 0.295     ,
       0.315     , 0.335     , 0.29833333, 0.32333333, 0.33166667,
       0.305     , 0.28166667, 0.30666667, 0.34      , 0.29833333,
       0.28833333, 0.33666667, 0.305     , 0.25166667, 0.31833333,
       0.285     , 0.29833333, 0.28666667, 0.32166667, 0.305     ,
       0.29666667, 0.32      , 0.33166667, 0.27666667, 0.335     ,
       0.28833333, 0.29666667, 0.31      , 0.26833333, 0.3       ,
       0.28      , 0.3       , 0.33166667, 0.29      , 0.30833333,
       0.29      , 0.29833333, 0.3       , 0.29166667, 0.29666667,
       0.305     , 0.30333333, 0.28333333, 0.29      , 0.3       ,
       0.3       , 0.3       , 0.295     , 0.305     , 0.29166667,
       0.27666667, 0.28333333, 0.325     , 0.275     , 0.30333333,
       0.29833333, 0.29666667, 0.31333333, 0.3       , 0.28333

In [4]:
import matplotlib.pyplot as plt
plt.hist(D, bins=10);

In [5]:
u=np.mean(D)
vari=np.var(D)

In [6]:
u

0.30104000000000003

In [7]:
vari

0.00035348506666666666

In [8]:
(0.3)*(1-0.3)/600

0.00035

In [9]:
nmb, value=np.histogram(D)

In [10]:
nmb

array([  4,  15,  34,  95, 133, 106,  61,  37,  11,   4], dtype=int64)

In [11]:
value

array([0.245 , 0.2565, 0.268 , 0.2795, 0.291 , 0.3025, 0.314 , 0.3255,
       0.337 , 0.3485, 0.36  ])

In [12]:
print('We are {0} percent sure that p is between {1} , {2} '.format(100*(np.sum(nmb[3:8]))/np.sum(nmb) ,  value[3] , value[7]))

We are 86.4 percent sure that p is between 0.27949999999999997 , 0.3255 
