In [1]:
import numpy as np

In [2]:
# List of 300,000 bernoulli random variable with 0.3 probability of being 1 
a=np.random.binomial(1, 0.3, 300000)

# First, we seperate list "a" into 500 parts. 
# List "d" contains the average of each part. In other words, each element is the average of 600 i.i.d. variables.
d = np.array([])
for i in range(500):
    c = a[i*600: (i+1) * 600]
    avg = np.mean(c)
    d = np.append(d, avg)
    

We expect that the elements of "d" follows a gaussian probability function with the average value of 0.3 and the variance of 0.3*(1-0.3)/600

In [3]:
d

array([0.30666667, 0.31666667, 0.27666667, 0.275     , 0.31666667,
       0.255     , 0.30666667, 0.285     , 0.26333333, 0.29166667,
       0.31333333, 0.31      , 0.29833333, 0.31833333, 0.31833333,
       0.27833333, 0.3       , 0.28166667, 0.30166667, 0.31666667,
       0.32      , 0.26833333, 0.28333333, 0.29666667, 0.29      ,
       0.31833333, 0.275     , 0.26833333, 0.315     , 0.29333333,
       0.32333333, 0.3       , 0.28166667, 0.28166667, 0.30833333,
       0.33      , 0.29166667, 0.315     , 0.32333333, 0.285     ,
       0.295     , 0.28166667, 0.29333333, 0.31      , 0.29333333,
       0.31333333, 0.27833333, 0.3       , 0.29333333, 0.305     ,
       0.29666667, 0.315     , 0.31      , 0.28      , 0.29333333,
       0.30666667, 0.28666667, 0.30333333, 0.28833333, 0.32666667,
       0.29      , 0.29333333, 0.305     , 0.27333333, 0.31333333,
       0.29833333, 0.29      , 0.26666667, 0.33166667, 0.29333333,
       0.28333333, 0.295     , 0.30166667, 0.28833333, 0.31166

In [4]:
import matplotlib.pyplot as plt
plt.hist(d, bins = 10);

In [5]:
average_d = np.mean(d)
variance_d = np.var(d)

In [6]:
average_d

0.29934333333333335

In [7]:
variance_d

0.0003273632333333333

In [8]:
(0.3)*(1-0.3)/600

0.00035

In [9]:
nmb, value = np.histogram(d)

In [10]:
nmb

array([  2,   0,  16,  37,  76, 135, 115,  74,  35,  10], dtype=int64)

In [11]:
value

array([0.23      , 0.24183333, 0.25366667, 0.2655    , 0.27733333,
       0.28916667, 0.301     , 0.31283333, 0.32466667, 0.3365    ,
       0.34833333])

In [14]:
print('We are {0} percent sure that the probability parameter'.format(100*(np.sum(nmb[3:8]))/np.sum(nmb))
      + ' is between {0}, {1} '.format(value[3], value[7]))

We are 87.4 percent sure that the probability parameter is between 0.2655, 0.3128333333333333 
