In [1]:
import numpy as np
from scipy.stats import norm
import random

a=np.random.normal(7.3, 3, ( 200))
a

array([ 9.23749874, 10.10597719,  7.13785841,  8.44088331,  7.62697166,
        3.15803424,  8.27667738, 11.83946835,  3.90189844,  0.36436693,
        7.20352038,  4.2211153 ,  9.96067075,  8.41738395,  4.36196332,
       10.83752794,  6.93785116, -0.04078607,  8.09837386,  8.42982956,
        8.40244061,  8.43993412,  5.85797306,  2.5917639 ,  7.02899557,
        9.11085228,  8.22238967, 10.05763024,  8.85434865,  8.40062692,
        6.60134609,  5.26517211,  7.96893522,  5.91580795, 11.01618504,
        5.97411059, -0.27577752,  5.49551238,  9.22053058,  5.55981608,
        7.14389221,  8.89465826, 13.20603026,  8.79023926,  4.2627382 ,
        9.81892963, 12.54679584, -1.20270554,  9.50795576,  1.74739818,
        6.22043375, 10.49682956,  8.46976507,  6.28273319,  8.9032959 ,
       11.28470019, 12.30892649,  8.69048683,  3.93344765,  9.26530684,
       10.75951871,  7.44350572,  8.0778913 , 10.11214688,  9.73317329,
        7.10808898,  4.42206967,  6.59075881, 10.29854238, 11.23

In [2]:
def Likelihood(x, mu, sd):
    LHo = 1
    for i in x:
        LHo = LHo*norm.pdf(i , mu, sd) 
    return LHo

In [3]:
Likelihood(a , 7.3        ,  3)

2.253364659242968e-219

### PSO

In [4]:
# initial
npop=125
population=np.hstack([np.random.uniform(low=-10, high=10, size=(npop,1)) , np.random.uniform(low=0, high=10, size=(npop,1))])
 
best_p=population
best_g=population[1,:]

Velocity=np.hstack([np.random.uniform(low=-0.1, high=0.1, size=(npop,1)) , np.random.uniform(low=0, high=0.1, size=(npop,1))])
best_P_OF=np.full(npop,0.0)
best_G_OF=0.0
print(population)
print(Velocity)

[[ 7.87980979  3.89714205]
 [-3.35441521  8.25000001]
 [-3.87054327  3.47990138]
 [ 5.15855811  9.46543197]
 [-1.97731967  4.41094446]
 [ 7.19497458  0.40607357]
 [ 0.67613204  7.2521398 ]
 [-9.10658245  4.77721703]
 [-0.97407013  1.3697169 ]
 [ 2.67545065  2.43894644]
 [-8.79630341  9.91169779]
 [ 1.10212292  7.11701915]
 [-0.65447699  6.11192939]
 [-5.82936052  8.49365972]
 [-1.85971477  5.11384765]
 [-4.19611348  5.68458322]
 [-9.57367729  7.54183512]
 [ 6.49709569  4.2212297 ]
 [ 1.85935607  0.75883909]
 [ 8.09644977  0.18648414]
 [ 5.9856879   9.27613255]
 [ 0.69978163  3.64057659]
 [-4.09762248  3.94495602]
 [ 1.92835045  2.46967294]
 [-3.71238682  5.11841482]
 [-9.79615666  2.84768478]
 [ 1.92752041  1.75153624]
 [ 7.57655408  2.65562874]
 [ 1.49418609  8.47029166]
 [-5.17351245  7.43920846]
 [ 5.27806332  3.65283417]
 [-7.7577526   6.96950005]
 [ 5.61792509  8.10642708]
 [-2.95674732  8.47301953]
 [ 5.70733409  7.37394262]
 [ 6.82695218  2.85776167]
 [-3.25977925  0.39600838]
 

In [5]:
# Inertia and acceleration 
ine , c1 , c2 = 0.9 , 0.25 , 0.25 

In [6]:
for itr in range(150):
    for x in range(npop):
        ind=population[x, :]
        LH=Likelihood(a , mu=ind[0]  , sd=ind[1])
        if LH>best_P_OF[x]:
            best_p[x, :]=ind
            best_P_OF[x]=LH
        if LH>best_G_OF:
            best_g=ind
            best_G_OF=LH
    for x in range(npop):
        rand1=random.random()
        rand2=random.random()
        Velocity[x, :]=ine*Velocity[x, :]+c1*rand1*(best_p[x, :]-population[x, :]) + c2*rand2*(best_g-population[x, :])
        Velocity[x, :]=np.clip(Velocity[x, :], [-0.2, 0], [0.2, 0.2])
        population[x, :]=population[x, :]+Velocity[x, :]
        population[x, :]=np.clip(population[x, :], [-13 , 0], [13,13])
        
                
          
        
        

In [7]:
best_g

array([7.23983282, 3.51641927])

In [8]:
best_p

array([[7.24040875, 3.89714205],
       [7.23561578, 8.31155108],
       [7.2420553 , 3.5167105 ],
       [7.23993631, 9.46543197],
       [7.23848548, 4.41094446],
       [7.24004718, 3.70238086],
       [7.23939882, 7.2521398 ],
       [7.20722453, 4.77721703],
       [7.24107107, 3.53941115],
       [7.23746772, 3.51641934],
       [7.24722645, 9.91169779],
       [7.24237131, 7.11701915],
       [7.24491415, 6.11192939],
       [7.23163974, 8.49365972],
       [7.2408749 , 5.11384765],
       [7.2426459 , 5.68458322],
       [7.23432997, 7.54183512],
       [7.23990967, 4.26888845],
       [7.24573755, 3.73255742],
       [7.24120547, 3.79028619],
       [7.23953546, 9.27613255],
       [7.23887243, 3.64057659],
       [7.24304653, 3.99615908],
       [7.23949011, 3.5164193 ],
       [7.23928507, 5.11841482],
       [7.22497444, 3.51641927],
       [7.23900754, 3.57718217],
       [7.23983282, 3.51641927],
       [7.2403318 , 8.47029166],
       [7.24144403, 7.43920846],
       [7.

In [9]:
best_G_OF

2.532818253290395e-219

In [10]:
best_P_OF

array([2.19537921e-224, 3.95396299e-270, 2.72272169e-221, 3.96882793e-280,
       1.66524286e-229, 2.41232825e-219, 4.67656218e-260, 1.77846736e-233,
       1.77609792e-221, 7.16271150e-221, 9.56596859e-284, 1.04510696e-258,
       3.17087722e-248, 9.00519422e-272, 3.24681563e-237, 1.47126470e-243,
       6.70942919e-263, 5.10426425e-228, 5.93541120e-223, 2.04148090e-219,
       1.49297987e-278, 3.22440782e-222, 2.62492365e-225, 4.73866708e-221,
       2.89031293e-237, 2.55116339e-221, 9.58711577e-222, 2.53281825e-219,
       1.45803574e-271, 6.70254955e-262, 2.59303500e-222, 3.22783838e-257,
       3.00768655e-268, 1.37849820e-271, 2.92600441e-261, 2.12877114e-219,
       1.88475750e-223, 4.90510376e-235, 8.15856000e-220, 2.55086202e-221,
       4.08248455e-279, 8.70276932e-250, 1.33314855e-222, 1.79197824e-256,
       3.92481274e-255, 7.49283891e-222, 5.50792636e-276, 5.03820447e-226,
       4.94962809e-242, 2.26112630e-252, 2.36006938e-223, 6.34219750e-222,
       1.23622900e-258, 2

In [11]:
LH

1.017347528002952e-246

In [12]:
population

array([[7.24040875, 3.89714205],
       [7.23561578, 8.31155108],
       [7.2420553 , 3.5167105 ],
       [7.23993631, 9.46543197],
       [7.23848548, 4.41094446],
       [7.24004718, 3.70238086],
       [7.23939882, 7.2521398 ],
       [7.20722453, 4.77721703],
       [7.24107107, 3.53941115],
       [7.23746772, 3.51641934],
       [7.24722645, 9.91169779],
       [7.24237131, 7.11701915],
       [7.24491415, 6.11192939],
       [7.23163974, 8.49365972],
       [7.2408749 , 5.11384765],
       [7.2426459 , 5.68458322],
       [7.23432997, 7.54183512],
       [7.23990967, 4.26888845],
       [7.24573755, 3.73255742],
       [7.24120547, 3.79028619],
       [7.23953546, 9.27613255],
       [7.23887243, 3.64057659],
       [7.24304653, 3.99615908],
       [7.23949011, 3.5164193 ],
       [7.23928507, 5.11841482],
       [7.22497444, 3.51641927],
       [7.23900754, 3.57718217],
       [7.23983282, 3.51641927],
       [7.2403318 , 8.47029166],
       [7.24144403, 7.43920846],
       [7.

In [13]:
Velocity

array([[ 6.94563927e-06,  0.00000000e+00],
       [-3.40097457e-03,  0.00000000e+00],
       [-7.16122279e-05,  0.00000000e+00],
       [ 1.14598031e-04,  0.00000000e+00],
       [ 3.36613593e-05,  0.00000000e+00],
       [-3.70001704e-04,  0.00000000e+00],
       [-1.41058579e-03,  0.00000000e+00],
       [ 3.50824112e-03,  0.00000000e+00],
       [ 2.58984758e-04,  0.00000000e+00],
       [-1.32385744e-03,  0.00000000e+00],
       [ 2.17526759e-03,  0.00000000e+00],
       [ 4.58001072e-04,  0.00000000e+00],
       [ 1.82080123e-03,  0.00000000e+00],
       [-8.94411340e-04,  0.00000000e+00],
       [ 2.49088399e-05,  0.00000000e+00],
       [ 7.16168920e-04,  0.00000000e+00],
       [ 5.48182113e-03,  0.00000000e+00],
       [-3.60767611e-05,  0.00000000e+00],
       [ 2.78530976e-04,  0.00000000e+00],
       [ 2.22670389e-06,  0.00000000e+00],
       [ 7.11450039e-05,  0.00000000e+00],
       [ 2.49209533e-04,  0.00000000e+00],
       [-7.26780443e-05,  0.00000000e+00],
       [ 2.