In [1]:
import numpy as np
from scipy.stats import norm
import random

In [2]:
a = np.random.normal(7.3, 3, (200)) # The list of 200 normal random variables with the average of 7.3 and standard deviation of 3
a

array([ 4.57954756,  5.31072215,  9.56073219,  8.54246485,  7.47045131,
        9.05417759,  6.32818875,  6.40563783,  8.39857233,  6.62237148,
        0.27002093,  3.10636654, 12.08489539, 10.24911634,  5.55922903,
        5.45831792,  6.9815093 , 10.16549061, 10.18538654,  4.97478742,
        9.24295831, 10.38870179, 11.27856956,  9.20827878,  3.50705823,
        9.77752325,  0.84976625,  7.92073667,  7.66775811,  7.64166404,
        7.87839821,  5.65089569,  5.98933383,  3.70537489,  4.64469164,
        8.44534586,  5.73681526,  2.88063903, 11.79121222,  7.87515707,
        7.91932445,  9.1429672 ,  6.46305381,  3.18324209, 12.07318129,
        4.84247901,  7.97241057, 12.3313809 ,  6.65842132,  2.96193387,
        6.73849743,  4.66961709,  6.05531577,  5.56385653, 11.15551652,
        8.90299735,  8.55338069,  7.28662204,  8.52778556,  9.23302774,
        3.3529497 ,  2.7889502 ,  9.73827294,  5.69130649,  6.81193349,
        6.00645648, 10.60409549,  7.8857434 ,  4.72282755,  5.37

In [3]:
def likelihood(x, mu, standard_dev):  
    likelihood_value = 1
    
    for i in x:
        likelihood_value = likelihood_value*norm.pdf(i, mu, standard_dev) 
    return likelihood_value

#This function compute the likelihood of the distribution of the data within liat "x" with
#a normal probability distribution with average of "mu" and standard deviation of "standard_dev"

In [4]:
likelihood(a, 7.3, 3)

2.8361797081366295e-216

### PSO

In [5]:
# initial
npop = 125 #Number of particles
population = np.hstack([np.random.uniform(low = -10, high = 10, size = (npop,1)), 
                        np.random.uniform(low = 0, high = 10, size = (npop,1))])
# The above lines builds an initial random population of particles
# with average in [-10, 10] interval and standard deviation in [0,10] 

# Each raw of the 'population' list is a particle [mu, standard_dev]

 
best_p = population
best_g = population[1,:]

velocity = np.hstack([np.random.uniform(low = -0.1, high = 0.1, size = (npop, 1)),
                      np.random.uniform(low = 0, high = 0.1, size = (npop, 1))])     #The initial random velocity

best_p_of = np.full(npop, 0.0)   #Initializing the best personal objective function (likelihood) of each particle
best_g_of = 0.0                  #Initializing the best global objective function (likelihood)
print(population)
print(velocity)

[[ 7.88812461  3.57252699]
 [ 8.73153908  3.96196768]
 [-2.58229119  2.69476465]
 [-9.33912232  7.40122824]
 [-7.38204394  8.17573786]
 [ 5.65781082  1.52251912]
 [ 5.58343485  2.49675776]
 [ 9.25957038  0.03588669]
 [ 8.90747374  2.2692597 ]
 [ 6.42976516  1.98507157]
 [ 1.30559389  8.45800977]
 [ 4.78173336  0.47340262]
 [-8.61172647  0.20440969]
 [-7.09677933  8.16580037]
 [-8.22521262  4.56742476]
 [ 7.19555595  1.1856571 ]
 [-9.8008662   9.71817818]
 [ 0.22044443  8.03471272]
 [ 6.27431584  0.7069812 ]
 [-9.30259861  2.61600661]
 [-4.12875657  8.77506051]
 [ 0.82286217  4.32681273]
 [-6.78457571  0.75460553]
 [ 5.38035971  4.55849911]
 [-7.74963519  1.08421994]
 [-6.51681889  1.30029534]
 [-9.79916481  1.88012795]
 [ 3.63781153  5.98072045]
 [ 6.98571822  6.11719533]
 [ 9.27020802  6.45523969]
 [-8.12934188  6.56441212]
 [-7.64184771  0.56787641]
 [ 6.48492827  8.21429139]
 [-8.23110875  9.4164317 ]
 [-6.0610672   9.15091366]
 [-3.19657436  1.71239122]
 [-0.09095043  5.91219552]
 

In [6]:
# Inertia and acceleration 
inertia, c1, c2 = 0.9, 0.25, 0.25 

In [7]:
for itr in range(250):    #Itterations of PSO optimizarion algorithm 
    
    for x in range(npop): 
        ind = population[x, :]
        lh = likelihood(a, mu = ind[0] ,standard_dev = ind[1])
        
        if lh > best_p_of[x]: #Updating best personal point
            best_p[x, :] = ind
            best_p_of[x] = lh
            
        if lh > best_g_of:
            best_g = ind
            best_g_of = lh
            
    for x in range(npop):
        rand1 = random.random()
        rand2 = random.random()
        
        velocity[x, :] = (0.99**itr)*inertia*velocity[x, :] + c1*rand1*(best_p[x, :] - population[x, :]) + c2*rand2*(best_g-population[x, :])
        velocity[x, :] = np.clip(velocity[x, :], [-0.2, 0], [0.2, 0.2])  #Updating velocities
        
        population[x, :] = population[x, :] + velocity[x, :]            
        population[x, :] = np.clip(population[x, :], [-13 , 0], [13,13]) #Updating the population
        
                
          
        
        

In [8]:
best_g

array([8.17550849, 3.78541259])

In [9]:
best_p

array([[8.17550849, 3.79359994],
       [8.17550849, 3.96196768],
       [8.17550849, 3.8203837 ],
       [8.17550849, 7.40122824],
       [8.17550849, 8.17573786],
       [8.17550849, 3.96840899],
       [8.17550849, 3.78589035],
       [8.17550849, 3.96346274],
       [8.17550849, 3.79327743],
       [8.17550849, 3.85295086],
       [8.17550849, 8.45800977],
       [8.17550849, 3.99233334],
       [8.17550849, 3.93798585],
       [8.17550849, 8.16580037],
       [8.17550849, 4.56742476],
       [8.17550849, 3.96480029],
       [8.17550849, 9.71817818],
       [8.17550849, 8.03471272],
       [8.17550849, 4.00732114],
       [8.17550849, 3.79306439],
       [8.17550849, 8.77506051],
       [8.17550849, 4.33140645],
       [8.17550849, 4.02902115],
       [8.17550849, 4.55849911],
       [8.17550849, 3.96453847],
       [8.17550849, 4.00811565],
       [8.17550849, 3.87394842],
       [8.17550849, 5.98072045],
       [8.17550849, 6.11719533],
       [8.17550849, 6.45523969],
       [8.

In [10]:
best_g_of

3.076828347467306e-216

In [11]:
best_p_of

array([1.19629055e-220, 3.08854550e-223, 8.08314438e-222, 5.00321995e-261,
       1.77808574e-268, 1.60936916e-216, 1.26638952e-218, 1.50125797e-217,
       8.61379421e-219, 2.89420403e-216, 4.54857801e-271, 2.57086066e-216,
       5.41889012e-223, 2.18666507e-268, 7.09530394e-230, 6.03400442e-217,
       6.67259332e-282, 3.70750483e-267, 2.19572848e-220, 1.39049648e-221,
       6.62656342e-274, 3.24310233e-227, 6.25917034e-224, 9.01847641e-230,
       2.83673028e-223, 1.01920412e-223, 2.39363261e-222, 4.81943878e-246,
       1.49070702e-247, 2.56565462e-251, 2.09748461e-252, 5.71378242e-224,
       7.80309330e-269, 2.06018591e-279, 3.60988440e-277, 6.42369289e-223,
       2.83263845e-245, 1.51530184e-271, 6.74196251e-236, 2.41924963e-216,
       2.70516814e-223, 2.07067732e-221, 3.61167287e-224, 1.45514508e-222,
       6.22807139e-259, 1.44391177e-229, 1.61725562e-274, 1.14280959e-246,
       3.18417954e-222, 1.08259016e-221, 1.64496851e-233, 1.87909383e-222,
       7.06708421e-228, 9

In [12]:
lh

1.8224853049100366e-271

In [13]:
population

array([[8.17550849, 3.79359994],
       [8.17550849, 3.96196768],
       [8.17550849, 3.8203837 ],
       [8.17550849, 7.40122824],
       [8.17550849, 8.17573786],
       [8.17550849, 3.96840899],
       [8.17550849, 3.78589035],
       [8.17550849, 3.96346274],
       [8.17550849, 3.79327743],
       [8.17550849, 3.85295086],
       [8.17550849, 8.45800977],
       [8.17550849, 3.99233334],
       [8.17550849, 3.93798585],
       [8.17550849, 8.16580037],
       [8.17550849, 4.56742476],
       [8.17550849, 3.96480029],
       [8.17550849, 9.71817818],
       [8.17550849, 8.03471272],
       [8.17550849, 4.00732114],
       [8.17550849, 3.79306439],
       [8.17550849, 8.77506051],
       [8.17550849, 4.33140645],
       [8.17550849, 4.02902115],
       [8.17550849, 4.55849911],
       [8.17550849, 3.96453847],
       [8.17550849, 4.00811565],
       [8.17550849, 3.87394842],
       [8.17550849, 5.98072045],
       [8.17550849, 6.11719533],
       [8.17550849, 6.45523969],
       [8.

In [14]:
velocity

array([[ 1.33632340e-016,  0.00000000e+000],
       [ 9.45309326e-017,  0.00000000e+000],
       [-3.09585885e-016,  0.00000000e+000],
       [ 2.89006607e-016,  0.00000000e+000],
       [ 8.05262952e-015,  0.00000000e+000],
       [ 4.66427593e-017,  0.00000000e+000],
       [ 4.03706577e-016,  0.00000000e+000],
       [ 3.88081411e-016,  0.00000000e+000],
       [-3.30431531e-016,  0.00000000e+000],
       [-2.02630854e-016,  0.00000000e+000],
       [ 8.98376413e-017,  0.00000000e+000],
       [ 4.22152611e-016,  0.00000000e+000],
       [ 2.83439221e-015,  0.00000000e+000],
       [-2.75486790e-016,  0.00000000e+000],
       [ 8.54471220e-016,  0.00000000e+000],
       [ 3.52769500e-016,  0.00000000e+000],
       [ 1.26366477e-014,  0.00000000e+000],
       [-3.58665531e-016,  0.00000000e+000],
       [ 3.07726081e-016,  0.00000000e+000],
       [ 1.56546159e-016,  0.00000000e+000],
       [-3.64008261e-016,  0.00000000e+000],
       [ 4.20013385e-016,  0.00000000e+000],
       [ 6

In [15]:
0.99**150

0.22145178723886091